### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by toreau**
Mostly focuses on the exit early strategy from methods.

### CODE REVIEW

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 6
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 9
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 22
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
- Added 23
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 21
- Added 24
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 21
- Added 25
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 22
- Added 29
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 22
- Added 28
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 25
- Added 33
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Thank you very much for this work @toreau 

However it nearly impossible to code review such a massive PR.  Is it possible for you to break this up into lots of small prs that change one thing each?

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Readers.cs  -3
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
+ Assets/Mirror/Editor/Weaver/Readers.cs  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Readers.cs  -3
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by toreau** [comment]
Even though changes seems huge, there's basically just minor changes all over the place to make the code - IMO - more readable and safe; exit early strategy, public to private/protected and what not. I need this stuff for mye OCD. :)

The biggest refactoring (...) I did, was with the Inject* methods inside Weaver/Processors/PropertySiteProcessor.cs. Two of those methods shared 99% of the same functionality...

For bigger changes, I'll of course divide the PRs into smaller batches.

**Comment by paulpach** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 32
- Added 39
           

Complexity increasing per file
==============================
- Assets/Mirror/Components/NetworkAnimator.cs  1
         

Clones removed
==============
+ Assets/Mirror/Editor/Weaver/Readers.cs  -3
+ Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/paulpach/MirrorNG/pullRequest?prid=5150399&bid=16915756)

**Comment by paulpach** [comment]
I don't dispute anything is bad...  I can't it is too big to see it all.

I can't merge it as is,  even if it is the best code in the world.

**Comment by toreau** [comment]
Ok. I won't dispute that, but that means I won't contribute in the future either. I just wanted to rip out the most minor bad behaviours before I started coding "for real."

**Comment by paulpach** [comment]
it is just basic netiquette.   Read this:

https://hackernoon.com/the-art-of-pull-requests-6f0f099850f9

**Comment by toreau** [comment]
No worries.

**Pull request closed without merging**
